# Generated by Django 2.2.3 on 2019-07-30 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20190730_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ticket', models.DateTimeField(auto_now_add=True)),
                ('mise', models.IntegerField()),
                ('gain', models.IntegerField()),
                ('choixcoureur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choix_coureur', to='profil.Coureur')),
            ],
        ),
    ]
