# Generated by Django 2.2.3 on 2019-07-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_ticket_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coureur',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
