# Generated by Django 2.2.3 on 2019-08-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_manbre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manbre',
        ),
    ]
